### ISSUE TITLE
Arduino Nano compatibility

### ISSUE THREAD

**Issue by bkenobi** [CapnBry/Powermon433#1]
I have the code running on an Uno without issue.  I wanted to shrink the setup, so I wrote the code to a Nano and hooked up the RF module.  I get the initial message in the serial monitor, but I don't see any data packets.  I am curious if this is related to the implementation of the interrupts.  I tested redirecting RF to the LED pin with a simple AttachInerrupt and DigitalWrite on pin 13 (all works as expected).

**Comment by bkenobi** [comment]
I forgot to mention that I'm using Arduino IDE 1.6.0.  I also confirmed that without altering anything, programming to the Uno works as well as programming a second Nano which does the same as the first.  This appears to be an issue with Nano's and compatibility with the Powermon433 code.

If there are any suggestions, I can test them out.  I have several RF receivers (superheterodyne and superregenerative), 2 Nano's, and 1 Uno, and an SDR USB stick that can be used to check different configurations.

**Comment by CapnBry** [comment]
Hi! I wish github alerted you when someone posts an issue. I just noticed this! As luck would have it, I bought a few Arduino Nanos just last week for another project. I hooked it up on the breadboard with a superregenerative receiver and it worked great, even better than I remembered it working.

It had been a while since I've used one of these as opposed to the RF69 I ended up using for "production" so there's some extra data output about the RxOokFloor and the RSSI which you should ignore because this type of receiver does not support it.

You might want to try commenting out the #define DPIN_RF69_RESET line near the top of the file, which doesn't attempt to enable the RF69 receiver. Maybe it's locking up at that point? It doesn't for me but it doesn't hurt to remove what you don't need.

In any instance there doesn't appear to be any issue with the Arduino Nano, which just uses an ATMega328 just like the Uno, so there is no pin name changes or anything. Not sure why your Nano doesn't work.
